GO-3027: Error Importing Object to Another Space
anyproto/anytype-heart pull request #1065
Opened 2024-04-02 12:56 UTC by AnastasiaShemyakinskaya

https://linear.app/anytype/issue/GO-3027/error-importing-object-to-another-space

Deleted linked objects were also exported. This leads to export error during single object export. 
So I skip exporting of deleted objects

2024-04-02 13:20 UTC, KirillSto commented on core/block/export/export.go
> +func (e *export) isLinkedObjectExist(rec []database.Record) bool {
We can make isLinkedObjectExist package-level func, as no fields or methods of export are used

2024-04-02 13:28 UTC, KirillSto approved these changes

2024-04-02 17:05 UTC, fat-fellow requested changes
Tests

2024-04-04 09:18 UTC, fat-fellow approved these changes

2024-04-04 09:25 UTC, merged