GO-3756 add required internal relations to all sbtype of objects
anyproto/anytype-heart pull request #1386
Opened 2024-07-11 18:59 UTC by requilence

We should add requiredInternalRelations to all objects, even a system ones. Because we set some local details such as "syncStatus" or "spaceId" to them. Currently this leads to ignoring of changes and creating a snapshot

2024-07-11 21:58 UTC, fat-fellow requested changes
tests

2024-07-12 09:35 UTC, fat-fellow approved these changes

2024-07-15 09:40 UTC, fat-fellow approved these changes

2024-07-15 10:35 UTC, deff7 commented on core/block/editor/state/state.go
> +	relLinks := s.GetRelationLinks()
GetRelationLinks copies from parent state making optimization not so useful

2024-07-15 15:09 UTC, merged