doc: enrich build instructions
anyproto/anytype-heart pull request #272
Opened 2023-08-05 23:48 UTC by SilverBut

---

- [x] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description

This PR adds some doc about protobuf issues, and require install `grpc-web` plugin.

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [x] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents

N/A

### Mobile & Desktop Screenshots/Recordings
N/A

### Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [x] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [ ] 🙅 no documentation needed

2023-08-05 23:49 UTC, SilverBut commented
I have read the CLA Document and I hereby sign the CLA

2023-08-07 11:04 UTC, fat-fellow commented on README.md
> +```bash
it can be simply shell

2023-08-07 17:16 UTC, requilence requested changes
Hi @SilverBut! Thanks for your first PR on anytype-heart ❤️

I've left some comments on the changes.

2023-08-09 21:31 UTC, SilverBut commented on README.md
> +brew link --overwrite protobuf@3
Indeed. But maybe users installed homebrew elsewhere (mine is `/usr/local/opt/protobuf@3/bin`). I'll add a memo to tell developers notice their terminal output.

2023-08-09 21:40 UTC, SilverBut commented on README.md
> +brew install protoc-gen-grpc-web
Removed. It's kind of weird...I was encountering failure when run `make setup-protoc` before I opened this pull request, but it works now after restart and clone repository again. Maybe my environment changed accidentally.

2023-08-09 22:01 UTC, SilverBut commented on README.md
> +brew install protoc-gen-grpc-web
Will a check of protoc version in Makefile helpful? To avoid unnecessary errors.

2024-09-13 16:17 UTC, closed without merging