GO-1500 Add snappy
anyproto/anytype-heart pull request #300
Opened 2023-08-14 09:40 UTC by KirillSto

---

- [ ] I understand that contributing to this repository will require me to agree with the [CLA](https://github.com/anyproto/.github/blob/main/docs/CLA.md)

---

### Description

### What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI

### Related Tickets & Documents

### Mobile & Desktop Screenshots/Recordings

### Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

### Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 [tech-docs](https://github.com/anyproto/tech-docs)
- [ ] 🙅 no documentation needed

### [optional] Are there any post-deployment tasks we need to perform?

2023-08-18 16:21 UTC, fat-fellow approved these changes

2023-08-18 17:09 UTC, cheggaaa requested changes

2023-08-18 17:09 UTC, cheggaaa commented on core/block/source/source.go
> +		res = data
In the case when you don't use snappy you shouldn't use sync.Pool because these bytes leaks outside this func.
Or you can just copy data to res

2023-09-01 17:08 UTC, cheggaaa approved these changes

2023-10-05 13:41 UTC, closed without merging