GO-2005: High memory usage detector
anyproto/anytype-heart pull request #439
Opened 2023-09-27 13:33 UTC by deff7

2023-09-27 14:03 UTC, requilence requested changes

2023-09-27 14:03 UTC, requilence commented on core/debug/profiler/profiler.go
> +		fmt.Println(base64.StdEncoding.EncodeToString(buf.Bytes()))
print

2023-09-28 10:11 UTC, fat-fellow approved these changes
Fix println pls

2023-10-23 09:45 UTC, requilence approved these changes

2023-10-23 10:00 UTC, merged